# Generated by Django 2.1.4 on 2019-01-12 04:24

from django.conf import settings
from django.db import migrations, models
import status.models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20190104_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(status.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
